Repository aicoe-aiops/ceph_drive_failure, pull requests merged in 2021-06, with the labels that each got.

#39 add chauhankaranraj and isabelizimm as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#37 rearrange file structure
  notebooks/data_sources/backblaze/backblaze2smartctl.ipynb
  notebooks/data_sources/backblaze/kaggle_hgst_end2end.ipynb
  notebooks/data_sources/backblaze/kaggle_seagate_end2end.ipynb
  notebooks/data_sources/backblaze/step0_smartctl_json_db_format_finder.ipynb
  notebooks/data_sources/backblaze/step0_smartctl_json_db_to_df.ipynb
  notebooks/data_sources/backblaze/step1_data_explorer.ipynb
  notebooks/data_sources/backblaze/step2a_data_cleaner_seagate.ipynb
  notebooks/data_sources/backblaze/step2b_data_cleaner_hgst.ipynb
  notebooks/data_sources/backblaze/step3a_clustering_and_binaryclf.ipynb
  notebooks/data_sources/backblaze/step3b_ternary_clf.ipynb
  notebooks/data_sources/backblaze/survival_analysis_exp.ipynb
  notebooks/data_sources/backblaze/to_smartctl_json.ipynb
Labels: approved, size/M

#41 Update links in blog
  docs/blog/hard-drive-failure-prediction-blog.md
Labels: lgtm, size/XS

#42 Update OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS
