Repository aicoe-aiops/ceph_drive_failure, pull requests merged in 2021-07, with the labels that each got.

#35 Add ADR for python module design
  docs/adr/0002-python-module-design.md
Labels: approved, size/L

#38 Telemetry data eda
  notebooks/data_sources/telemetry/step0_EDA.ipynb
Labels: approved, size/XXL

#47 Reorganize Content for Operate First website
  README.md
  docs/content.md
  docs/get-started.md
  docs/how-to-contribute.md
Labels: approved, lgtm, size/L
